services:
  - type: web
    name: face-recognition-server
    runtime: python
    region: singapore
    plan: free
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y \
        libwebp-dev \
        libwebp7 \
        libwebpdemux2 \
        libwebpmux3 \
        cmake \
        build-essential
      
      # Then install Python packages
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: true
