services:
  - type: web
    name: face-recognition-server
    runtime: docker  # Changed from 'python' to 'docker'
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile  # Path to your Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: true
