services:
  - type: web
    name: face-recognition-server
    runtime: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      apt-get update && apt-get install -y cmake build-essential
    startCommand: gunicorn server:app --timeout 120 --workers 1 --threads 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: true